---
- hosts: kubernetes
# become: true
  user: root

  tasks:
  - name: deploy app on kubernetes
    command: kubectl apply -f deployement.yml

  - name: create service for app
    command: kubectl apply -f service.yml


