---
- hosts: localhost
# become: true
  user: root

  tasks:
  - name: deploy app on kubernetes
    command: kubectl apply -f /var/lib/jenkins/workspace/pipeline-tp/deployement.yml

  - name: create service for app
    command: kubectl apply -f /var/lib/jenkins/workspace/pipeline-tp/service.yml


